### ISSUE TITLE
[BUG] Context menu broken on gecko

### ISSUE THREAD

**Issue by vertigo220** [rohanb10/snoozz-tab-snoozing#22] opened 2021-01-02 22:35 UTC
## Description

No right-click menu entry on tabs and clicking on buttons in add-on popup does nothing.

## Expected Behavior

Add-on should do stuff.

## Actual Behavior

Add-on doesn't do anything.

## How to Reproduce (if applicable)

Install add-on and try to use it.

## Your Device
* Browser and version: Waterfox Classic 2020.12 x64
* OS: Win10x64 v20H2
* Device Resolution (UI related bugs only)

## Which Page

All

## Screenshots / Videos / Logs
N/A

**Comment by rohanb10** [comment] 2021-01-03 07:41
hello Waterfox is not officially supported for this extension. I have a lot of other new features I have lined up before i would like to think about supporting a new browser. I have added this to my list of things to do, but it is extremely low priority and I cannot guarantee that I will continue to to support it. I'm just a single developer doing this in my free time and testing it across three major browsers already.

**Comment by vertigo220** [comment] 2021-01-03 08:00
Waterfox is nearly identical to Firefox, being a fork of it (and even calling it that is a stretch). I've never run across a Firefox add-on that doesn't also work in Waterfox, so I have a hard time believing that's the problem. Maybe this add-on requires a higher version (Quantum), which would be fine, but if that's the case, that should be specified. If that's not the case, then it seems likely the issue has to do with something else, and I would have been happy to help figure it out, but it seems there's no interest in doing so.

**Comment by rohanb10** [comment] 2021-01-04 14:52
I didnt do a ton of googling so didn't realise waterfox and ff have the same kind of relationship like edge and chrome. I thought it would be another marketplace to sign up for and constantly update with new releases.

I downloaded a copy of Waterfox today and I can't reproduce what you were saying exactly. The popup works fine for me, I can click on all of the buttons and works as expected.

Rightclick/context menu is not working for me, but i made a fix for this exact bug a few weeks ago. I have not deployed a new version in a while so the fix isn't live yet. Hopefully will deploy this week with some new features and bug fixes

**Comment by rohanb10** [comment] 2021-01-04 14:54
Let me know if anything else is broken and I'll take a look

**Comment by vertigo220** [comment] 2021-01-04 16:15
Which Waterfox did you try, Classic or G3? Just tried going through settings, changed theme to dark but pop-up is still light-themed, and clicking "CONFIGURE" and "SHOW" under the context menu and keyboard shortcuts options doesn't do anything. The drop-downs do respond, though. Also, not sure if it's normal, but when I click the icon, the pop-up looks like this:

![image](https://user-images.githubusercontent.com/12024557/103555355-221b6a80-4e7e-11eb-935d-b2913e9fc96f.png)

**Comment by rohanb10** [comment] 2021-01-07 12:57
didnt realise there was two different forks of waterfox.

Unfortunately I will not be able to support waterfox classic. Classic does not support a lot of modern ES6+ javascript syntax improvements and shortcuts which are used all over the codebase. To include support for them I would have to rewrite a fair bit of logic, and it would definitely slow down the dev process in the future. If I am going to use any fancy features from the WebExtension API (which I definitely plan to do), they will not work out of the box in WF classic

I know this isn't what you wanted to hear, but it would be best if you could use the G3 Waterfox since I plan to have full support for the latest versions of Firefox. If you want/ are interested, you can fork this repo and I can help you get it working but I do not want to bloat up this tiny extension with code for a single legacy browser with very low usage.

**Comment by rohanb10** [comment] 2021-01-07 12:59
Also I was not able to find any good sources for extension documentation for waterfox classic. If you know of any let me know and I'll take a look. Hard to figure out what APIs are missing

**Comment by vertigo220** [comment] 2021-01-07 14:56
That's fine, and I understand completely. My only issue is that if it's not compatible with older versions due to the use of WE API, it should make that clear on AMO, to avoid users wasting time installing it and trying to figure out how to get it working, not to mention your time in dealing with those help requests. At the very least, a note should be made in the description, though the minimum version should be set in the add-on, to inform AMO to gray out the install buttons on browsers older than that. I realize that's the cost of using the older version, but I choose to do so because I need certain add-ons that don't work with the newer Firefox (Quantum) and Waterfox (G3). I don't blame you, I blame Mozilla for killing off XUL before having the WE API even close to ready to replace them, without giving developers near enough time to convert their add-ons, and without having the API expanded enough for some add-ons to convert even years later. They dropped the ball and lost a lot of users because of it.

As for sources for documentation, probably the best bet would be to contact the Waterfox team, but it doesn't sound likely that it would make much difference, and I certainly would't want you to go to a lot of effort on my account. I'm not even sure if this add-on would be of much use to me, and I wouldn't want you spending a bunch of time on it only to have me try it and not find it helpful. I mainly just wanted to make sure there wasn't an issue with it.

**Closed** 2021-05-14 11:26 UTC
Labels: bug, waiting for release
