### ISSUE TITLE
[BUG] custom snooze with future year not possible

### ISSUE THREAD

**Issue by RandomClaim** [rohanb10/snoozz-tab-snoozing#21] opened 2020-12-31 13:24 UTC
## Description
Hey,

I tried to snooze a tab till tomorrow with a custom time. Since today is the last day of the year, I changed the year to 2021. Happy new Year by the way!

## Expected Behavior
Tab closes and reopens on the given date, respecting the chosen year

## Actual Behavior
When trying to press the 'snoozz' button, the fields containing the date started blinking red the same way it does when selecting another invalid date (e.g. something in the past)

## How to Reproduce (if applicable)
Choose a year in the future when selecting a custom time.

## Your Device
* Browser and version: Firefox 84.0.1 AND Vivaldi 3.5.2115.81
* OS: Windows 10 20H2

## Which Page
Popup

## Screenshots / Videos / Logs
![trying to select date](https://user-images.githubusercontent.com/9338392/103412101-e037af00-4b73-11eb-9436-0ac4f09fd0ba.png)

**Comment by rohanb10** [comment] 2021-01-03 07:45
Hi can you check again to see if this is still  broken for you? I was not able to reproduce it even if I changed the year to 2022. Regardless, in the next release I am changing the way you select a custom time/date using the library [flatpickr](https://flatpickr.js.org/examples/) for better compatibility and consistency across browsers.

**Comment by RandomClaim** [comment] 2021-01-03 13:29
Still not working, both on Vivaldi and Firefox. However, I just tried it on the chromium version of Edge, works as expected there. 

Could the Installation method play a role with that? Edge is pre-installed on Windows. I used [Scoop](https://github.com/lukesampson/scoop) to install Vivaldi and Firefox, which (from my understanding) uses the portable versions of those programs (which I did not think of being an issue previously)

Anyways, this issue probably won't affect me until next December. Thank you for your fast response!

![Vivaldi and Firefox](https://user-images.githubusercontent.com/9338392/103479569-e2497a00-4dce-11eb-8297-f69daf89bf81.png)

**Comment by rohanb10** [comment] 2021-01-04 14:57
I don't think method of installation would play a difference at all. I'm just using standard web ext apis, nothing fancy. Anyways this is guaranteed to be fixed by next december lol, along with a lot of other options for custom time and dates

**Closed by rohanb10** 2021-01-04 14:57 UTC
Labels: bug
