### ISSUE TITLE
[FEATURE] Sound notification

### ISSUE THREAD

**Issue by Funkadelik** [rohanb10/snoozz-tab-snoozing#73] opened 2021-11-04 12:14 UTC
##  Description
Please add sound notification for waking up tabs. And I dont know its a bug or my browser settings, but I can't see any notification. Option "Snoozz Notifications" turn on.
## Your Setup
Chrome 95.0.4638.69

**Comment by rohanb10** [comment] 2022-03-09 18:39
Duplicate of #52 - please follow there for updates

**Closed by rohanb10** 2022-03-09 18:39 UTC
