### ISSUE TITLE
[BUG] Same tab opens twice

### ISSUE THREAD

**Issue by zappe** [rohanb10/snoozz-tab-snoozing#11] opened 2020-10-15 19:55 UTC
## Description
Sometimes a tab open twice after been asleep

## Expected Behavior
Only open one

## Actual Behavior
Open twice

## How to Reproduce (if applicable)
Sleep a tab, but it's intermittent.

## Your Device
* Browser and version: Firefox 81.0.2
* OS: macOS 10.15.7
* Device Resolution (UI related bugs only)

## Which Page
N/A

## Screenshots / Videos / Logs
N/A

**Comment by rohanb10** [comment] 2020-10-16 08:59
Hmm I thought I saw this while testing these last few days. Was not able to reproduce it so I just assumed it was a one-off error due.

I'm still not able to reproduce this, snoozing tabs or windows. Regardless, I have added some small changes to the code in https://github.com/rohanb10/snoozz-tab-snoozing/commit/adb91fd7515186f57fcd41f77face63fe1fe2c1d that may resolve this. Leaving this issue open just in case you or anyone else sees it again

**Comment by rohanb10** [comment] 2020-10-19 11:45
New version 2.3.0 is out on CWS and FF Addon store. Your browser should update the add-on automatically. 

Let me know if the bug still exists. I have not seen it in the last ~3 days, but I also only saw it once before. Hard to reproduce this one so I'm just gonna leave this open for a week or two in case it pops up

**Comment by zappe** [comment] 2020-10-19 20:01
I'll give it a try, thanks!

**Comment by zappe** [comment] 2020-10-28 16:53
Today I got the issue again

**Comment by rohanb10** [comment] 2020-10-29 08:22
Damn. I made some changes to make tabs wake up promptly at the scheduled time and I guess this is just a fallout from that. Will try to narrow down which change is causing this.

**Comment by rohanb10** [comment] 2020-10-29 12:33
hey @zappe . Just curious, how many days have you set your `history` setting to? You can find it on the **Settings** page under **"Automatically delete tabs after"**

I have a process that clears old tabs, and this might trigger the process to wake up tabs again. I have no idea if this is what's causing the bug, but it's the lead I have rn.

**Comment by zappe** [comment] 2020-10-29 21:12
7 days

**Comment by adamcdavies** [comment] 2020-10-30 12:46
If it helps, I'm seeing this behaviour too. Started a few days ago and seems to be happening most of the time now.
I'll monitor and test some scenarios to see if it's all the time. I usually have several tabs snoozed, so maybe there's something there.
My auto delete option is set to 1 year.
Firefox V 82.0.1
MAC 10.15.7

**Comment by rohanb10** [comment] 2020-11-04 12:03
Finally was able to (accidentally) reproduce the bug on my machine. I have just pushed a new commit https://github.com/rohanb10/snoozz-tab-snoozing/commit/78fb11de35ef61fd6ef04ba9b786de3b631fdd12 which will hopefully put an end to this. Testing for the next 24ish hours and then hopefully can deploy before friday.

**Comment by rohanb10** [comment] 2020-11-05 17:28
Just released [`2.3.1`](https://github.com/rohanb10/snoozz-tab-snoozing/releases/tag/v2.3.1) which should hopefully fix this. It's live on firefox and probably soon on chrome.

Version number is now shown on the settings page, so if you can see that you're using the latest version.

Keep me posted

**Comment by zappe** [comment] 2020-11-11 20:10
Still having the issue with 2.3.1

**Comment by mkeroppi** [comment] 2020-11-14 17:59
I can confirm the same on 2.3.1 - sometimes tab opening more than twice.

This seems to happen when it's opening a large number of tabs at the same time.

**Comment by rohanb10** [comment] 2020-11-23 17:04
Praying that this commit will fix this d0ea6b504b602640c526629df9a9834e96bccbaa 🙏 

Basically applying a 10 second debounce to the function that opens up tabs and windows. New release later this week.

**Comment by rohanb10** [comment] 2020-11-25 07:18
It did not 😢. 

but I got a new reproducible error with the most recent changes. Am pushing out a new release with more fixes (v2.3.2.2). Should be released in the next few hours on FF, maybe half a day on Chrome

**Comment by mkeroppi** [comment] 2020-11-27 04:45
Sort of fixed for me. I can see that it's still opening a number of tabs but it's closing the extra tabs almost immediately after.

**Comment by zappe** [comment] 2020-12-12 18:08
Still an issue for me.

**Comment by adamcdavies** [comment] 2020-12-19 21:57
So far, so good, for me; haven't seen the issue for the last couple of weeks.

**Comment by rohanb10** [comment] 2020-12-24 10:25
@zappe can you tell me if this is still happening consistently for you? if it does happen, can you let me know the number of different tabs / windows that are **supposed** to be opening (not duplicates)

All the other users that I've spoken to have mentioned that this issue has not not cropped up again in the last 2-3 weeks.

**Comment by zappe** [comment] 2020-12-26 21:39
Only once I believe.

**Closed** 2021-05-17 22:03 UTC
Labels: bug
